version: '3.8'

services:

    #PHP 8 Service
    webapp:
        container_name: ut-php-8
        build:
            args:
                user: 0 # $ echo $USER
                uid: 501 # $ id -u
            context: .
            dockerfile: ./Dockerfile
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - phpnet
        depends_on:
            - mysqlapp
        ports:
            - "9000:9000"
        links:
            - nginxapp
            - mysqlapp
        restart: unless-stopped
    
    #Nginx Service
    nginxapp:
        container_name: ut-nginx
        image: nginx:latest
        ports:
                - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/site.conf
        networks:
                - phpnet
        links:
            - mysqlapp
        restart: unless-stopped
    
    # DB - MySQL 5.7
    mysqlapp:
        container_name: ut-mysql-57
        image: mysql:5.7
        platform: linux/x86_64
        environment:
            MYSQL_PORT: 3306
            MYSQL_ROOT_PASSWORD: pass123
            MYSQL_DATABASE: userstransactions
            MYSQL_USER: user
            MYSQL_PASSWORD: pass123
        command:
            - --explicit_defaults_for_timestamp
            - --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/volumes/mysql/data:/var/lib/mysql
            #- ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
            #- ./docker/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        networks:
            - phpnet
        restart: unless-stopped

#Docker Networks
networks:
    phpnet:
        driver: bridge