version: '3.8'

services:

    #PHP 8 Service
    php-fpm:
        container_name: ut-php-8
        image: php:8-fpm
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html/
        networks:
            - phpnet
        depends_on:
            - mysql
            - nginx
        links:
            - nginx
            - mysql
        restart: unless-stopped
    
    #Nginx Service
    nginx:
        container_name: ut-nginx
        image: nginx:latest
        hostname: userstransactions.local
        ports:
              - "80:80"
        volumes:
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        networks:
              - phpnet
        links:
            - mysql
        restart: unless-stopped
    
    # DB - MySQL 5.7
    mysql:
        container_name: ut-mysql-57
        image: mysql:5.7
        platform: linux/x86_64
        env_file:
            - .env
        environment:
            MYSQL_PORT: ${DB_PORT}
            MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
            MYSQL_DATABASE: ${DB_DATABASE}
        command:
            - --explicit_defaults_for_timestamp
            - --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
        ports:
            - "${DB_PORT}:${DB_PORT}"
        networks:
            - phpnet
        restart: unless-stopped

#Docker Networks
networks:
    phpnet:
        driver: bridge