version: '3.8'

services:

    #PHP 8 Service
    webapp:
        container_name: ut-php-8
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - ut-network

    # NGINX Service
    ut-nginx:
        image: nginx:alpine
        container_name: ut-nginx-alpine
        restart: unless-stopped
        tty: true
        ports:
            - "${APP_EXTERNAL_PORT:-80}:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - ut-network
        
    # DB - MySQL 8.0
    ut-mysql:
        image: mysql/mysql-server:8.0.23
        container_name: ut-mysql-8
        tty: true
        command:
            - --default-authentication-plugin=mysql_native_password
            - --explicit_defaults_for_timestamp
        ports:
            - "${DB_EXTERNAL_PORT:-3306}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: '%'
        volumes:
            - utdbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - ut-network

#Docker Networks
networks:
    ut-network:
        driver: bridge

#Volumes
volumes:
    utdbdata:
        driver: local