name: "Action Laravel"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: userstransactions
          MYSQL_ROOT_PASSWORD: 'pass123'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan jwt:secret -n
        php artisan config:cache
        php artisan cache:clear

    - name: Run Swagger suit
      run: composer swagger-check
      
    - name: Run PHPStan suit
      run: composer phpstan

    - name: Run PHP Code Sniffer suit
      run: composer phpcs

    - name: Run PHP Unit Tests suite
      env:
        DB_HOST: mysql
        DB_PORT: 3306
        DB_DATABASE: userstransactions
        DB_USER: root
        DB_PASSWORD: pass123
      run: composer tests